# Standard
import os
import socket
from pathlib import Path

# Remote
from pydantic_settings import BaseSettings


def _find_env_file() -> str | None:
    """
    Search for .env.hermes-client in order:
        1. Current working directory
        2. User home directory
        3. %APPDATA%/Hermes  (Windows)
    :returns: The first path found, or None.
    """
    candidates = [
        Path.cwd() / ".env.hermes-client",
        Path.home() / ".env.hermes-client",
    ]
    appdata = os.environ.get("APPDATA")
    if appdata:
        candidates.append(Path(appdata) / "Hermes" / ".env.hermes-client")

    for path in candidates:
        if path.exists():
            return str(path)
    return None


def default_env_file_path() -> Path:
    """
    Return the preferred path for writing a new .env.hermes-client file.
    Chooses %APPDATA%/Hermes/ on Windows, home directory otherwise.
    """
    appdata = os.environ.get("APPDATA")
    if appdata:
        d = Path(appdata) / "Hermes"
        d.mkdir(parents=True, exist_ok=True)
        return d / ".env.hermes-client"
    return Path.home() / ".env.hermes-client"


class ClientSettings(BaseSettings):
    SERVER_URL: str = "http://localhost:8000"
    CLIENT_NAME: str = socket.gethostname()
    LOCAL_HOST: str = "0.0.0.0"
    LOCAL_PORT: int = 9000

    # Resolved at configure-time and persisted to .env.hermes-client.
    # Left blank so the startup logic knows to prompt/resolve them if missing.
    CALLBACK_URL: str = ""
    ADO_USER_ID: str = ""
    ADO_DISPLAY_NAME: str = ""

    # ADO credentials — used once during `configure` to resolve identity.
    # Stored in the env file so `run` can re-resolve on demand if needed.
    ADO_ORGANIZATION_URL: str = ""
    ADO_PAT: str = ""

    SUBSCRIPTIONS: list[str] = ["pr", "workitem", "pipeline", "manual"]

    model_config = {
        "env_file": _find_env_file(),
        "env_file_encoding": "utf-8",
    }

    def is_fully_configured(self) -> bool:
        """True when all required runtime fields are present."""
        return bool(
            self.SERVER_URL
            and self.CALLBACK_URL
            and self.ADO_USER_ID
            and self.ADO_DISPLAY_NAME,
        )

    def write_env_file(self, path: Path | None = None) -> Path:
        """Write current settings to an .env.hermes-client file.
        Creates the file (and parent directories) if it doesn't exist.
        """
        target = path or default_env_file_path()
        target.parent.mkdir(parents=True, exist_ok=True)

        lines = [
            "# Hermes Client Configuration — auto-generated by `hermes-client configure`",
            "# Edit manually or re-run `hermes-client configure` to update.",
            "",
            f"SERVER_URL={self.SERVER_URL}",
            f"CLIENT_NAME={self.CLIENT_NAME}",
            f"LOCAL_HOST={self.LOCAL_HOST}",
            f"LOCAL_PORT={self.LOCAL_PORT}",
            f"CALLBACK_URL={self.CALLBACK_URL}",
            "",
            "# ADO identity (resolved from PAT by hermes-client configure)",
            f"ADO_ORGANIZATION_URL={self.ADO_ORGANIZATION_URL}",
            f"ADO_PAT={self.ADO_PAT}",
            f"ADO_USER_ID={self.ADO_USER_ID}",
            f"ADO_DISPLAY_NAME={self.ADO_DISPLAY_NAME}",
            "",
            f"SUBSCRIPTIONS={self.SUBSCRIPTIONS}",
        ]
        target.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return target
